// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAdminIdentitiesByIdData, GetApiAdminIdentitiesByIdErrors, GetApiAdminIdentitiesByIdResponses, GetApiAdminIdentitiesData, GetApiAdminIdentitiesPendingData, GetApiAdminIdentitiesPendingErrors, GetApiAdminIdentitiesPendingResponses, GetApiAdminIdentitiesResponses, GetApiAuthMeData, GetApiAuthMeErrors, GetApiAuthMeResponses, GetApiUserProfileData, GetApiUserProfileErrors, GetApiUserProfileResponses, GetApiUserStatusData, GetApiUserStatusResponses, GetHealthData, GetHealthResponses, PatchApiAdminIdentitiesByIdApproveData, PatchApiAdminIdentitiesByIdApproveErrors, PatchApiAdminIdentitiesByIdApproveResponses, PatchApiAdminIdentitiesByIdRejectData, PatchApiAdminIdentitiesByIdRejectErrors, PatchApiAdminIdentitiesByIdRejectResponses, PostApiAdminCreateData, PostApiAdminCreateErrors, PostApiAdminCreateResponses, PostApiAuthLoginData, PostApiAuthLoginErrors, PostApiAuthLoginResponses, PostApiAuthRegisterData, PostApiAuthRegisterErrors, PostApiAuthRegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Register a new user
 *
 * Submit personal information and an ID photo.
 * The account starts in `PENDING` status and must be approved by an admin before login is possible.
 *
 */
export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostApiAuthRegisterResponses, PostApiAuthRegisterErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Authenticate and receive a JWT
 *
 * Returns a JWT only for `CONFIRMED` users.
 * `PENDING` users receive a `403` prompting them to wait for review.
 * `REJECTED` users receive a `403` with the rejection reason.
 *
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiAuthLoginResponses, PostApiAuthLoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the currently authenticated user
 */
export const getApiAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiAuthMeResponses, GetApiAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * Get the authenticated user's full profile
 */
export const getApiUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserProfileData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserProfileResponses, GetApiUserProfileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/profile',
    ...options
});

/**
 * Get identity status (lightweight polling endpoint)
 */
export const getApiUserStatus = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserStatusData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserStatusResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/status',
    ...options
});

/**
 * Create an admin account
 *
 * **Two ways to authenticate:**
 * 1. `x-admin-secret` header — use for bootstrapping the very first admin.
 * 2. Bearer JWT of an existing admin — for creating subsequent admins.
 *
 */
export const postApiAdminCreate = <ThrowOnError extends boolean = false>(options: Options<PostApiAdminCreateData, ThrowOnError>) => (options.client ?? client).post<PostApiAdminCreateResponses, PostApiAdminCreateErrors, ThrowOnError>({
    security: [{ name: 'x-admin-secret', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List PENDING identity submissions
 */
export const getApiAdminIdentitiesPending = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminIdentitiesPendingData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminIdentitiesPendingResponses, GetApiAdminIdentitiesPendingErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/identities/pending',
    ...options
});

/**
 * List all identities (optional status filter)
 */
export const getApiAdminIdentities = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminIdentitiesData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminIdentitiesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/identities',
    ...options
});

/**
 * Get full detail of a single identity
 */
export const getApiAdminIdentitiesById = <ThrowOnError extends boolean = false>(options: Options<GetApiAdminIdentitiesByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiAdminIdentitiesByIdResponses, GetApiAdminIdentitiesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/identities/{id}',
    ...options
});

/**
 * Approve a PENDING identity
 *
 * Changes status to `CONFIRMED` and sends a confirmation email.
 */
export const patchApiAdminIdentitiesByIdApprove = <ThrowOnError extends boolean = false>(options: Options<PatchApiAdminIdentitiesByIdApproveData, ThrowOnError>) => (options.client ?? client).patch<PatchApiAdminIdentitiesByIdApproveResponses, PatchApiAdminIdentitiesByIdApproveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/identities/{id}/approve',
    ...options
});

/**
 * Reject a PENDING identity
 *
 * Changes status to `REJECTED` and sends a rejection email with the reason.
 */
export const patchApiAdminIdentitiesByIdReject = <ThrowOnError extends boolean = false>(options: Options<PatchApiAdminIdentitiesByIdRejectData, ThrowOnError>) => (options.client ?? client).patch<PatchApiAdminIdentitiesByIdRejectResponses, PatchApiAdminIdentitiesByIdRejectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/identities/{id}/reject',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
