// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | 'https://your-production-domain.com' | (string & {});
};

export type IdentityStatus = 'PENDING' | 'CONFIRMED' | 'REJECTED';

export type Role = 'USER' | 'ADMIN';

export type UserPublic = {
    id?: string;
    fullName?: string;
    fatherName?: string;
    motherName?: string;
    dateOfBirth?: string;
    placeOfBirth?: string;
    email?: string;
    idPhotoUrl?: string;
    role?: Role;
    status?: IdentityStatus;
    rejectionReason?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type Pagination = {
    page?: number;
    limit?: number;
    total?: number;
    pages?: number;
};

export type ErrorResponse = {
    message?: string;
};

export type ValidationErrorResponse = {
    message?: string;
    errors?: Array<{
        field?: string;
        message?: string;
    }>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is running
     */
    200: {
        status?: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostApiAuthRegisterData = {
    body: {
        fullName: string;
        fatherName: string;
        motherName: string;
        dateOfBirth: string;
        placeOfBirth: string;
        email: string;
        /**
         * Must contain at least one uppercase letter and one number.
         */
        password: string;
        /**
         * JPEG, PNG, or WebP — max 5 MB.
         */
        idPhoto: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Email already in use
     */
    409: ErrorResponse;
    /**
     * ID photo exceeds 5 MB
     */
    413: ErrorResponse;
    /**
     * Unsupported image format
     */
    415: ErrorResponse;
    /**
     * Validation error
     */
    422: ValidationErrorResponse;
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
    /**
     * Registration successful
     */
    201: {
        message?: string;
        user?: UserPublic;
    };
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponse;
    /**
     * Account is PENDING or REJECTED
     */
    403: {
        message?: string;
        status?: IdentityStatus;
        reason?: string;
    };
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        message?: string;
        /**
         * Bearer JWT
         */
        token?: string;
        user?: UserPublic;
    };
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetApiAuthMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Identity PENDING or REJECTED
     */
    403: unknown;
};

export type GetApiAuthMeResponses = {
    /**
     * Current user profile
     */
    200: {
        user?: UserPublic;
    };
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type GetApiUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type GetApiUserProfileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Identity not CONFIRMED
     */
    403: unknown;
};

export type GetApiUserProfileResponses = {
    /**
     * User profile
     */
    200: {
        user?: UserPublic;
    };
};

export type GetApiUserProfileResponse = GetApiUserProfileResponses[keyof GetApiUserProfileResponses];

export type GetApiUserStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/status';
};

export type GetApiUserStatusResponses = {
    /**
     * Current identity status
     */
    200: {
        status?: IdentityStatus;
        rejectionReason?: string;
    };
};

export type GetApiUserStatusResponse = GetApiUserStatusResponses[keyof GetApiUserStatusResponses];

export type PostApiAdminCreateData = {
    body: {
        fullName: string;
        fatherName: string;
        motherName: string;
        dateOfBirth: string;
        placeOfBirth: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/create';
};

export type PostApiAdminCreateErrors = {
    /**
     * Missing or invalid secret / JWT
     */
    401: unknown;
    /**
     * Email already in use
     */
    409: unknown;
};

export type PostApiAdminCreateResponses = {
    /**
     * Admin created
     */
    201: {
        message?: string;
        admin?: UserPublic;
    };
};

export type PostApiAdminCreateResponse = PostApiAdminCreateResponses[keyof PostApiAdminCreateResponses];

export type GetApiAdminIdentitiesPendingData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/admin/identities/pending';
};

export type GetApiAdminIdentitiesPendingErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Admin role required
     */
    403: unknown;
};

export type GetApiAdminIdentitiesPendingResponses = {
    /**
     * Paginated list of PENDING users
     */
    200: {
        data?: Array<UserPublic>;
        pagination?: Pagination;
    };
};

export type GetApiAdminIdentitiesPendingResponse = GetApiAdminIdentitiesPendingResponses[keyof GetApiAdminIdentitiesPendingResponses];

export type GetApiAdminIdentitiesData = {
    body?: never;
    path?: never;
    query?: {
        status?: IdentityStatus;
        page?: number;
        limit?: number;
    };
    url: '/api/admin/identities';
};

export type GetApiAdminIdentitiesResponses = {
    /**
     * Paginated list of users
     */
    200: {
        data?: Array<UserPublic>;
        pagination?: Pagination;
    };
};

export type GetApiAdminIdentitiesResponse = GetApiAdminIdentitiesResponses[keyof GetApiAdminIdentitiesResponses];

export type GetApiAdminIdentitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/identities/{id}';
};

export type GetApiAdminIdentitiesByIdErrors = {
    /**
     * User not found
     */
    404: unknown;
};

export type GetApiAdminIdentitiesByIdResponses = {
    /**
     * User detail
     */
    200: {
        data?: UserPublic;
    };
};

export type GetApiAdminIdentitiesByIdResponse = GetApiAdminIdentitiesByIdResponses[keyof GetApiAdminIdentitiesByIdResponses];

export type PatchApiAdminIdentitiesByIdApproveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/identities/{id}/approve';
};

export type PatchApiAdminIdentitiesByIdApproveErrors = {
    /**
     * User not found
     */
    404: unknown;
    /**
     * Identity is not PENDING
     */
    409: unknown;
};

export type PatchApiAdminIdentitiesByIdApproveResponses = {
    /**
     * Identity approved
     */
    200: {
        message?: string;
        user?: UserPublic;
    };
};

export type PatchApiAdminIdentitiesByIdApproveResponse = PatchApiAdminIdentitiesByIdApproveResponses[keyof PatchApiAdminIdentitiesByIdApproveResponses];

export type PatchApiAdminIdentitiesByIdRejectData = {
    body: {
        reason: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/identities/{id}/reject';
};

export type PatchApiAdminIdentitiesByIdRejectErrors = {
    /**
     * User not found
     */
    404: unknown;
    /**
     * Identity is not PENDING
     */
    409: unknown;
    /**
     * Reason is required
     */
    422: unknown;
};

export type PatchApiAdminIdentitiesByIdRejectResponses = {
    /**
     * Identity rejected
     */
    200: {
        message?: string;
        user?: UserPublic;
    };
};

export type PatchApiAdminIdentitiesByIdRejectResponse = PatchApiAdminIdentitiesByIdRejectResponses[keyof PatchApiAdminIdentitiesByIdRejectResponses];
